# ==================================================================
# Data Source
# ==================================================================
spring:
  # ==================================================================
  # h2 database
  # ==================================================================
  h2:
    console:
      enabled: true
      path: /h2

  # ==================================================================
  # thymeleaf
  # ==================================================================
  thymeleaf:
    cache: false

  # ==================================================================
  # show a log of SQL query
  # ==================================================================
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

    # ==================================================================
    # Hibernate ddl auto (create, create-drop, update)
    # ==================================================================
    hibernate:
      ddl-auto: update
    # ==============================================================
    # = The SQL dialect makes Hibernate generate better SQL for the chosen database
    # ==============================================================
    database-platform: org.hibernate.dialect.H2Dialect

